// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdv3ofiFAxyuL07bxj47x2Y7XDBqS6lh0',
    appId: '1:282138688908:web:9a67eea5f01fb1280faaa9',
    messagingSenderId: '282138688908',
    projectId: 'intellifarm-45bdd',
    authDomain: 'intellifarm-45bdd.firebaseapp.com',
    storageBucket: 'intellifarm-45bdd.firebasestorage.app',
    measurementId: 'G-R9WKY01GE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz76739G-sJCG1Bk1LDRg2btBwPNkBgfw',
    appId: '1:282138688908:android:c56ac4d0c828511c0faaa9',
    messagingSenderId: '282138688908',
    projectId: 'intellifarm-45bdd',
    storageBucket: 'intellifarm-45bdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWPxbtgO1FfucXCwQkQnlDnjOsb0VRn_U',
    appId: '1:282138688908:ios:1b75398fd1d46fdf0faaa9',
    messagingSenderId: '282138688908',
    projectId: 'intellifarm-45bdd',
    storageBucket: 'intellifarm-45bdd.firebasestorage.app',
    androidClientId: '282138688908-msdnmte36l9p0gsmui2jc2tlg7t86cb0.apps.googleusercontent.com',
    iosClientId: '282138688908-3e5h2300pb756ev53jrd55gs7gbbebmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellifarmClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWPxbtgO1FfucXCwQkQnlDnjOsb0VRn_U',
    appId: '1:282138688908:ios:1b75398fd1d46fdf0faaa9',
    messagingSenderId: '282138688908',
    projectId: 'intellifarm-45bdd',
    storageBucket: 'intellifarm-45bdd.firebasestorage.app',
    androidClientId: '282138688908-msdnmte36l9p0gsmui2jc2tlg7t86cb0.apps.googleusercontent.com',
    iosClientId: '282138688908-3e5h2300pb756ev53jrd55gs7gbbebmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellifarmClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdv3ofiFAxyuL07bxj47x2Y7XDBqS6lh0',
    appId: '1:282138688908:web:779b4ca778e78baf0faaa9',
    messagingSenderId: '282138688908',
    projectId: 'intellifarm-45bdd',
    authDomain: 'intellifarm-45bdd.firebaseapp.com',
    storageBucket: 'intellifarm-45bdd.firebasestorage.app',
    measurementId: 'G-NK8S03S0FL',
  );
}
